services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=sparkle'
      - 'POSTGRES_PASSWORD=sparkle'
      - 'POSTGRES_USER=sparkle'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
